version: 0.1

phases:
  install:
    commands:
      - npm install 
  build:
    commands:
      - npm test -- ci > buildresult.txt 
  post_build:
    commands:
      - sh spec/clean-test-resources.sh

artifacts:
  files:
    - buildresult.txt
  discard-paths: yes
